/**
 * General application data constants.
 */
export const APPLICATION_CONSTANTS = {
  PRIVACY_POPUP_STATUS: 'PRIVACY_POPUP_STATUS',
  BROWSER_X_GUID: 'X-GUID',
  CUSTOM_API_ENDPOINT: 'CUSTOM_API_ENDPOINT',
}
